### ISSUE TITLE
Consider removing "Daily Reward" column for Liquidity Details

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1013]
Previously, this was helpful for users to be able to make sure they were getting the right payouts at distribution time. Now, it will be something constantly changing as people stake/unstake LP tokens any time of day. I'd like to recommend to remove it and simplify the UI, also less opportunity to report wrong numbers if there's a bug.

@parrot9design

**Comment by parrot9design** [comment]
Definitely not in favour of removing this. It’s always been an approximation because the behaviour of other users will obviously affect it, but it’s helpful for users to get an indication of the rewards they can expect for supplying liquidity.

By this logic, if we remove the daily rewards column here, we should also remove the loan rewards from the position details section.
