### ISSUE TITLE
Add forum link to transaction data on vote page

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1111]
This is now a required parameter in the transaction, please update the FE to account for this.

<img width="1061" alt="Screen Shot 2022-11-07 at 2 29 21 PM" src="https://user-images.githubusercontent.com/43685868/200397777-f745c1cb-cdde-4b00-8742-04ffd82e97e9.png">

**Comment by AntonAndell** [comment]
Interface looks like this:
`defineVote(String name, String description, BigInteger vote_start, BigInteger duration, String forumLink, @Optional String transactions) `

Where the restrictions so forumlink is that is starts with https://gov.balanced.network/

**Comment by hetfly** [comment]
@BennyOptions forum link already is in the transaction data and is required however the format isn't enforced. That could be done, however it would still be impossible to create votes through the UI because of the change from `@Optional String actions` to `@Optional String transactions`

`transactions` param has dramatically different behaviour compared to the earlier `actions` param version and will be quite time consuming to refactor. I'm not sure if that fits into our current priorities.
