### ISSUE TITLE
Color change for slippage percentage

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#1139]
Would be good to incorporate a sliding gradient of color - darkest red being closest to 100%, green being closest to 0. Should be some skew, as 0-1% is green, but anything over 1% should start changing color rapidly. 10% slippage could be dark red instead of 100%. These are just example numbers. Maybe Uniswap [repo](https://github.com/Uniswap/interface) has a benchmark. If you can find what Uniswap uses, please use that.

<img width="376" alt="Screen Shot 2022-12-21 at 12 03 58 AM" src="https://user-images.githubusercontent.com/43685868/208825974-f421e137-f2aa-4698-a222-1235fcc839ee.png">

<img width="478" alt="Screen Shot 2022-12-21 at 12 06 57 AM" src="https://user-images.githubusercontent.com/43685868/208826117-8a8c2e12-70ef-4c4b-8f0b-09ee3a80c62d.png">

**Comment by parrot9design** [comment]
Let's handle this more subtly.

We only need to indicate when the slippage is high, not when it's at an ideal level (because that should be expected). Green is the colour used for links, so should not be used in this situation.

We only use one shade of red, so let's not start diversifying the colour palette. If the slippage is above an amount we consider ideal (whether that's 1.5% or 5%+), we should display the value in `#fb6a6a`.

In future, these design details should be run past us before assigning to a developer, as we'll likely have a different view on the execution.
