### ISSUE TITLE
 Integrate stability fund swaps via router

### ISSUE THREAD

**Issue by hetfly** [balancednetwork/balanced-network-interface#1328]

**Comment by AntonAndell** [comment]
In the new version of the router a new payable method is added:
`routeV2(byte[] _path, @Optional BigInteger _minReceive, @Optional String _receiver) `
And a new choice for data on the tokenFallback.
Instead of using JSON these new methods uses RLP encoded Data:
The _path is now a RLP List<RouteAction>
And a RouteAction is: 
RLP  [int action, Address toToken]
    public String receiver;
    public BigInteger minimumReceive;
    public List<RouteAction> actions;
And for the tokenFallback Data it now takes:
RLP [
String method
String receiver
BigInteger minimumReceive
List<RouteAction> _path
]

method is still "_swap" like in json
receiver and minimumReceive are optional and can be nullable in RLP
_path pararmeter is the same as in the routeV2 method.

Current actions are:
    static final int SWAP = 1;
    static final int STABILITY_SWAP = 2;

**Comment by hetfly** [comment]
@parrot9design I think it would be more efficient to let @0xmilktea do it while I review the AVAX connection and work on the Loans UI

**Comment by FezBox** [comment]
Have reassigned to @0xmilktea 

@0xmilktea something you and @swiftcc624 can tackle?

**Comment by FezBox** [comment]
Ready for testing in 2 days
