### ISSUE TITLE
Locking BALN UI/UX (bBALN)

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#542]
@parrot9design please come up with a design for the staking BALN process. Please refer to the video here to see what process users will need to go through to maximize their rewards

https://resources.curve.fi/guides/boosting-your-crv-rewards

**Comment by BennyOptions** [comment]
https://dao.curve.fi/

**Comment by BennyOptions** [comment]
targeting end of week for the design completion

**Comment by parrot9design** [comment]
You can preview the design for this here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/

## Wallet
Let's start with the most obvious change: we've moved the wallet up to the top right so it's accessible from every page. At the moment if you click `ICX`, you'll get a modal to interact with that asset, but we may contain it to the dropdown. In other words, this part is still a WIP, better to focus on that after the heavy lifting is done.

![Screen Shot 2021-10-31 at 4 11 45 PM](https://user-images.githubusercontent.com/63842577/139565566-017bb913-2326-498c-a9f4-960708c607da.png)

---

## Rewards
The rewards panel is now full-width:
![Screen Shot 2021-10-31 at 4 12 04 PM](https://user-images.githubusercontent.com/63842577/139565580-45ae0684-882d-48e4-9237-790686efae9d.png)

Claiming rewards works just as it always has. All the new functionality is in the right-hand section.

### Locking BALN

![Screen Shot 2021-10-31 at 4 19 10 PM](https://user-images.githubusercontent.com/63842577/139565805-a7262aab-01cc-40c7-b0e9-229d8e410525.png)
![Screen Shot 2021-10-31 at 4 19 19 PM](https://user-images.githubusercontent.com/63842577/139565811-839404b1-bf98-40e3-9102-bc2101748ba8.png)

- bBALN value increases as you increase the slider or adjust the lockup period, which also changes the 3 values displayed underneath
- Once locked, all shorter time periods should be hidden during future adjustments (i.e. if BALN is locked for 1 year when adjustments are made, only `1 year`, `2 years`, `4 years` should be displayed).


![Screen Shot 2021-10-31 at 4 20 58 PM](https://user-images.githubusercontent.com/63842577/139565848-ba35d9fe-ff29-4b2f-ad42-03190c995c87.png)
- Once locked, if you move the slider to the left to withdraw BALN, you'll see a warning about a 50% fee.

#### Network fees

- May need to show 4 decimal precision instead of 2 in order for it to be of any value to most people.
- May also include a `?` that includes the trailing 30-day APY, or the amount of BALN they'd have received based on their current % (see https://github.com/balancednetwork/balanced-network-interface/issues/726 – will include in next steps)

#### Liquidity APY
![Screen Shot 2021-10-31 at 4 00 45 PM](https://user-images.githubusercontent.com/63842577/139565153-eb3cb2c0-3635-4b9a-95de-09082bcf28de.png)
- Show a max of 4 pools per row. 
- Use a single boost value (e.g. `2.1 x`) if the user has one pool, or a range from highest to lowest boost.

### Confirmation modals
![Screen Shot 2021-10-31 at 4 15 26 PM](https://user-images.githubusercontent.com/63842577/139565639-92c17e0e-4463-4b31-923e-1afb64b0cfbb.png)
- If possible, we should show an estimated date based on UTC/blockchain data, like we have for the current BALN unstaking UX.

![Screen Shot 2021-10-31 at 4 16 08 PM](https://user-images.githubusercontent.com/63842577/139565644-9620d4ba-ad4e-42bb-aef1-6691eb26085d.png)

----

## Next steps

We still need to:
- finalise the wallet design
- make the onboarding flow as seamless as possible
- display network fee projections

so I've kept us assigned to the issue, but the rest is ready for development. Happy to answer any questions/explain the flow in more depth if needed.

**Comment by parrot9design** [comment]
### Onboarding state

If a user hasn't got any BALN in their wallet, the Rewards section should look like this:
![Screen Shot 2021-11-22 at 3 08 02 PM](https://user-images.githubusercontent.com/63842577/142790660-afc956e3-5b85-4720-a8bc-272db8b480ee.png)
(Code is [here](http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/) under `Rewards empty state`. To view it, remove the `hide` class.)


### Wallet design

The wallet will show every asset that you can interact with in the Balanced UI, listed from highest to lowest value. You can search by asset name or ticker to find the one you want faster.

![Screen Shot 2021-11-22 at 3 15 56 PM](https://user-images.githubusercontent.com/63842577/142791261-04b302b7-ab44-4878-b13e-8d214c553ee2.png)

The wallet should be accessible from every page, much like the dropdown is now.

Click an asset from the wallet to open a modal with the actions you can take. All assets except ICX/sICX will only have the option to Send (for now):

![Screen Shot 2021-11-22 at 3 16 33 PM](https://user-images.githubusercontent.com/63842577/142791301-aca9e721-1658-41da-a6e0-01dc5a0e8c99.png)

There is a bug with the sICX entry at the moment, but you get the idea. We may make a few adjustments to the sICX/ICX Unstake/Unstaking tabs to enhance that interaction, but for now we can implement it as it currently works. Note that BALN will no longer have a Staking tab.


We'll leave the network fee APY alone for now and work on including it on the Stats page instead, as it would require us to add more surrounding details to provide the right context, which magnifies the complexity.

**Comment by parrot9design** [comment]
Because the APY for each liquidity pool will vary so much based on bBALN, let’s also add the user’s APY to the supply liquidity section to make it more accessible:

![88BC4822-0637-4207-95D4-9DE3A8414531](https://user-images.githubusercontent.com/63842577/143836317-c45603cc-6c23-4e8c-8680-acff84600262.jpeg)

**Comment by hetfly** [comment]
Waiting for API integration and actual reward boosting calculations
