### ISSUE TITLE
Proposal Type: DAO Spending

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#669]
@parrot9design we need a new proposal form for DAO Disbursements.

@dbrehmer please confirm the params taken by the contract. This is what I believe we need in the design/frontend

Need to think about if we want people to be able to disburse multiple token types in one vote

User Inputs
- Type of token to disburse (can take multiple types)
- Amount of token to disburse (can take multiple tokens)
- Disbursement Address

Display
- Types of tokens in the DAO Fund
- Amounts of each token

**Comment by BennyOptions** [comment]
User inputs:

- Type of token to disburse:

**Comment by BennyOptions** [comment]
Should have design done tomorrow

**Comment by parrot9design** [comment]
We’ve added a `Funding` proposal type here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/vote/new-proposal/

The asset selector isn’t active as it would’ve required more heavy lifting with javascript, but it should be similar to the Swap variation, but with `Balance` instead of `Wallet`:

![BFFE66BA-1619-434F-BDF0-06318DC1405D](https://user-images.githubusercontent.com/63842577/134594295-0f475764-0504-42b7-ba66-4b369525df75.jpeg)

You can see what a Funding proposal looks like after it’s been submitted here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/vote/proposal/

Let us know if you have any questions.

**Comment by BennyOptions** [comment]
Input validation against getBalances API @Chunn @tuan-tl 

https://tracker.icon.foundation/contract/cx835b300dcfe01f0bdb794e134a0c5628384f4367#readcontract

**Comment by BennyOptions** [comment]
@dbrehmer please leave a testnet transaction of this as a comment here
