### ISSUE TITLE
Think of a better way to display all APYs in the app for incentivized pools

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#949]

**Comment by parrot9design** [comment]
Let's turn the `Liquidity details` section into `Liquidity pools`, and have it always appear if you have the `Supply liquidity` tab open. It has different states based on whether you're signed in or not, similar to the Omm markets and liquidity pools.

If you're signed out or haven't supplied any liquidity, you should see all available pools, in the same format as we have on the Stats page:
<img width="1067" alt="Screen Shot 2022-05-20 at 4 03 27 PM" src="https://user-images.githubusercontent.com/63842577/169448292-65ac4c5c-9637-4649-9268-b164d33f55ec.png">

- We should show the BALN + Fee APYs, as in https://github.com/balancednetwork/balanced-network-info/pull/83.
- We should allow for the ability to sort the pools based on any of the table headers.
- Let's add pagination after 10 pools to prevent the section from getting too overwhelming.
- You should be able to search any token to see the available pools. If possible, that would include searching via contract address to see pools available for a custom token, but we can add that later if it's too intensive.
- If you click on a pool, its details should load in the `Supply liquidity` section so it's easier to supply (especially when signed in).


If you're signed in and have supplied liquidity, you should be able to toggle between your pools and all pools: 
<img width="600" alt="Screen Shot 2022-05-20 at 4 02 35 PM" src="https://user-images.githubusercontent.com/63842577/169448896-96df757b-cf98-45f8-bcf2-d8652bb5a819.png"><img width="600" alt="Screen Shot 2022-05-20 at 4 02 52 PM" src="https://user-images.githubusercontent.com/63842577/169448908-a50f7669-5b97-4559-9046-db778f25b2ea.png">

If you click on a pool in the `Your pools` section, it will expand down to allow for LP token staking and withdrawals, and should become the active pool in the `Supply liquidity` section so it's easier to supply additional liquidity.

If possible, let's fit this into the Java smart contract / continuous rewards release (in the next week or two), so we can release one big update for the liquidity details section instead of staging it in two parts. Creating a branch off https://github.com/balancednetwork/balanced-network-interface/pull/770 is likely the way to go.

Base design is here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/trade/
