### ISSUE TITLE
UX around interacting with the Stability Fund

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-network-interface#975]
It would be good to allow users to interact with the Stability Fund directly. Let's think about the best way to do this. The functionality allows users to swap whitelisted assets (currently IUSDC and USDS) for bnUSD for 1:1 minus a 0.5% fee. Depending on how much is left in the stability fund, the users can also swap bnUSD back for any of the whitelisted assets 1:1 minus a 0.5% fee.

**Comment by parrot9design** [comment]
@BennyOptions thoughts on this?

<img width="435" alt="Screen Shot 2022-05-13 at 5 38 48 PM" src="https://user-images.githubusercontent.com/63842577/168222659-42f83783-1e1a-45e8-9b84-be3ccc275f91.png">
<img width="497" alt="Screen Shot 2022-05-13 at 6 19 14 PM" src="https://user-images.githubusercontent.com/63842577/168222908-669fd4c0-1df1-4169-bfe4-5387a01aebd9.png">


![Screen Shot 2022-05-13 at 17 39 38](https://user-images.githubusercontent.com/63842577/168222663-eff9f3ab-c2df-4383-8cdd-50465ad950e2.png)


- The link text option would only appear when a value is entered into either input field
- The option won't appear if the Stability Fund is empty for the direction you're taking


If the Stability Fund can only partially cover your swap, the value should display the maximum possible:
<img width="385" alt="Screen Shot 2022-05-13 at 6 23 24 PM" src="https://user-images.githubusercontent.com/63842577/168223682-54f87d9b-7c27-47ee-857f-c46449ce9c29.png">
![Screen Shot 2022-05-13 at 18 28 55](https://user-images.githubusercontent.com/63842577/168224268-d92c4136-fe87-4739-ba9f-f4b6195b29e6.png)

**Comment by BennyOptions** [comment]
I like all this except how we handle for if the stability fund can only service a partial fill of the trade. Not sure I have a better suggestion lol but I feel like if I enter "2000" and see "Stability Fund = 1,000", I wouldn't even consider it, even if it were a better deal for that 1,000. It seems like it's offering me at a 50% fee/premium

**Comment by parrot9design** [comment]
Here's where we landed with this UI. We wanted the link text to be more specific so that edgecases are automatically handled, but we also needed to present it in a way that keeps the UI balanced (there'd be too much space on the chart if the text was underneath like in the previous comments).

![Screen Shot 2022-05-20 at 2 13 23 PM](https://user-images.githubusercontent.com/63842577/169434986-4f8ecb16-d066-46e6-af43-efacf9f2a3bc.png)

- The tooltip should only appear when a value is entered into either input field for relevant swaps
- It shouldn't appear if the Stability Fund is empty for the direction you're taking
- If the Stability Fund doesn't have enough to cover the amount entered into the input fields, it should show the max trade size available

Although not included in the prototype (the logic would have delayed this further), hovering over the `?` should show a tooltip message off to the side with this content:

>The Stability Fund allows you to mint or burn bnUSD 1:1 for approved stablecoins.

If you click/tap the link text, you'll get the regular swap confirmation modal:


![](https://user-images.githubusercontent.com/63842577/168224268-d92c4136-fe87-4739-ba9f-f4b6195b29e6.png)

You can find the design (sans logic) here: http://balanced-development.s3-website-us-east-1.amazonaws.com/prototype-dev/trade/
